// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ScanScreenshots():Promise<void>;

export function SearchScreenshots(arg1:string):Promise<void>;
