// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ScanScreenshots() {
  return window['go']['main']['App']['ScanScreenshots']();
}

export function SearchScreenshots(arg1) {
  return window['go']['main']['App']['SearchScreenshots'](arg1);
}
